version: '3.4'

services:
  softplan.juros.calculojurosapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  softplan.juros.taxajurosapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

